// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFVqBti7G_qUsqj0ILWvZ5VOSR3c4RNKY',
    appId: '1:1060938454449:web:0e1124795f355aae1c1990',
    messagingSenderId: '1060938454449',
    projectId: 'sh-express-transport',
    authDomain: 'sh-express-transport.firebaseapp.com',
    storageBucket: 'sh-express-transport.appspot.com',
    measurementId: 'G-MPDMY0CDTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIdPj2fLZSk3gdYRWR_jKTvJcFUPYKbtU',
    appId: '1:1060938454449:android:5510150b12f3ddc11c1990',
    messagingSenderId: '1060938454449',
    projectId: 'sh-express-transport',
    storageBucket: 'sh-express-transport.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAao3DrIGXlnbSKlGJzU2hF09kWHfHkKiw',
    appId: '1:1060938454449:ios:e4e8a450ead945251c1990',
    messagingSenderId: '1060938454449',
    projectId: 'sh-express-transport',
    storageBucket: 'sh-express-transport.appspot.com',
    iosClientId:
        '1060938454449-72ov620c8l7aco47db99hidq9l71rhs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.shExpressTransport',
  );
}
